config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users, only: [:show, :new, :create, :update]do
    collection do
      get 'search'
      get 'search_result'
    end
    end
  resources :groups, only: [:index, :create]do
      resources :messages, only: [:index, :create]
    end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  # accepts_nested_attributes_for :group_users
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users

  def be_friend?(current_user)
    tmp = true
    groups.each do |group|
      if group.users.pluck(:id).include?(current_user.id)
        tmp = false
        break
      else
        tmp = true
      end
    end
    return tmp
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # def after_sign_out_path_for(resource)
  #   'users/sign_in'
  # end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # def index
  #   @users = []
  #   current_user.groups.each do |group|
  #     group.users.each do |user|
  #       unless user.id == current_user.id
  #         @users << user
  #         @users.uniq!{|user|user.id}
  #       end
  #     end
  #   end
  # end

  def index
    @groups = current_user.groups
  end

  def create
    group = Group.new
    group.users << User.find(create_params[:user_id])
    group.users << current_user
    group.save
    redirect_to action: :index

  end

  private
  def create_params
    params.require(:group).permit(:user_id)
  end

#   def create
#     binding.pry
#     @group = Group.new(group_params)
#     binding.pry
#     @group.users << current_user
#     @group.save
#     redirect_to action: :index
#   end


#   private

#   def group_params

#     params.require(:groupgroup).permit(user_ids: [])
#   end
# end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @group = Group.find(params[:group_id])
    @messages = @group.messages #.order(created_at DESC)
    @message = Message.new
    @users = @group.users
  end

  # def detail
  #   # binding.pry
  #   @messages = Message.where('(user_id = ?) or (receiver_id = ?) and (user_id = ?) or (receiver_id = ?)' , current_user.id,current_user.id,params[:user_id],params[:user_id]).order('created_at DESC')
  #   @message = Message.new
  #   @user = User.find(params[:user_id])
  # end

  # # def index
  # #   @messages = Message.where(receiver_id: current_user.id).order('created_at DESC')
  # # end

  def create
    @group = Group.find(params[:group_id])
    @messages = @group.messages
    Message.create(create_params)


  end

  private
  def create_params
    params.require(:message).permit(:body, :group_id).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order('created_at DESC').limit(5)
  end

  def show
    @user = User.find(params[:id])
    @group = Group.new
  end

  def search
  end

  def search_result
    @users = User.where("(adress1 = ?) or (age >= ?) and (age <= ?) or (work = ?)", params[:add], params[:agemin], params[:agemax], params[:work])
  end

  def new
    # @user = User.new
    @user = current_user
  end

  def update
    current_user.update(update_params)
    redirect_to root_path
  end



private
  def update_params
    params.require(:user).permit(:nickname, :adress1, :adress2, :age, :numchild, :work, :private, :frequeny, :ivent, :lastname, :comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<ul>
<% @groups.each do |group| %>
    <% group.users.each do |user| %>
      <% unless user.id == current_user.id %>
        <li>
        <%= user.nickname %>
        <%= link_to "トークルーム", group_messages_path(group.id)%>
        </li>
      <% end %>
    <% end %>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>ママトモひろば</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ママ友広場</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><a href=""><%= current_user.nickname %>がログイン</a></li>
        <li><a href="/groups">友達一覧</a></li>
        <li><%=link_to 'サインアウト', "/users/sign_out", method: :delete %></li>
        <li><a href="/users/new">アカウント</a></li>
      <% else %>
        <li><a href="/users/sign_in">サインイン</a></li>
        <li><a href="/users/sign_up">新規登録</a></li>
      <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
    <li>
      <%= message.user.nickname %>さん　　→　　
      <%= message.body %>
    </li>

app/views/messages/create.js.erb
$("#message_body").val("");
$(".message").html("<%= j(render @messages) %>");

app/views/messages/index.html.erb
<div class="container-fluid">
 <% @users.each do |user| %>
 <%= user.nickname %>さん
 <% end %>
 のトークルーム
 <br><br>
<tr align="center" valign="middle">
 <td height="30" colspan="7" valign="top">
 <%= image_tag ('f_border.gif') %>
 <%= image_tag ('f_border.gif') %>
 <%= image_tag ('f_border.gif') %>
</td>
</tr>
<br><br>
 <ul class="message">
 <%= render @messages %>
  </ul>
  <br><br>


<%= form_for [@group,@message], remote: true do |f| %>
メッセージを送る
 <%= f.text_area :body %>
 <%=f.hidden_field :group_id, value: @group.id %>
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
    <% end %>
</div>

app/views/messages/show.html.erb
<div class="container-fluid">
<h2>メッセージルーム<h2>
 <ul class="thumbnails thumbnail--movies row grid4 js-lazy-load-images js-my-check-stats" id="list-module">
   <% @messages.each do |message| %>
<span class="label label-warning"><%= message.sender %>"さんと<%= message.receiver %>さんのページ</span>
<% end %>

<%= form_for @message do |f| %>
  <div class="col-sm-2">メッセージを送る</div>
  <div class="form-for input-sm" style="padding: 3px;">
 <%= f.text_area :message, class: "form-conrol" %>
  </div>
  </div>
        <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
</div>

app/views/users/_user.html.erb
<ul style="list-style:none;">
   <div>
   <div class="col-sm-4">
           <div class="mama-box">
          <div class="panel-body">
            <li>
              <h3 datetime="<%= user.created_at %>">
              <%= time_ago_in_words(user.created_at) %>前
              <h3>
            </li>
             <li>
                 <a href="/users/<%= user.id %>" title="<%= user.nickname %>">
                     <%= user.nickname %>　さん
                  </a>
             </li>
             <li>
                 <h3 title="<%= user.adress1 %>">
                     <%= user.adress1 %>　在住
                  </h3>
             </li>
             <li>
                 <h3 title="<%= user.age %>">
                     <%= user.age %>　才
                  </h3>
             </li>
                  <li>
                 <h3 title="<%= user.comment %>">
                     <%= user.comment %>　
                  </h3>
             </li>
      </div>
    </div>
</div>
 </div>
 </ul>
 

app/views/users/index.html.erb
<div class="container-fluid">

 <div class="jumbotron" body bgcolor="#fff0f5" >
   <div class="container-fluidyokoso">
    <h1>ようこそ！ママトモひろばへ</h1>
     <p>ママ友が欲しいけど、面倒な付き合いはしたくないと思っているあなた。
        大丈夫です。事前にどんなママとどんな付き合い方がしたいのか情報を交換して、安心してママ友を見つけましょう。</p><br>
     <div >
     <p>早速ママ友を探してみましょう！</p>
    <p><a class="btn btn-primary btn-lg" href="/users/search" role="button">ママ友を探す</a></p>
     </div>
  </div>
 </div>

<div>
<h2>新着ママ友<h2>

 <%= render partial: "user", collection: @users %>

 </div>


</div>

app/views/users/new.html.erb
<div class = "container-fluid">
 <div class="row">
 <h4>プロフィール</h4>
<%= form_for @user do |f| %>
  <div class="col-sm-6">ニックネーム</div>
  <div class="form-for input-sm" style="padding: 3px;">
 <%= f.text_field :nickname, class: "form-conrol" %>
  </div>
  </div>
      <div class="col-sm-6">住所</div>
    <div class="form-for input-sm" style="padding: 3px;">
    都道府県
 <%= f.select :adress1, [["北海道","北海道"],["青森県","青森県"],["秋田県","秋田県"],["岩手県","岩手県"],["山形県","山形県"],["宮城県","宮城県"],["福島県","福島県"],["山梨県","山梨県"],["長野県","長野県"],["新潟県","新潟県"],["富山県","富山県"],["石川県","石川県"],["福井県","福井県"],["茨城県","茨城県"],["栃木県","栃木県"],["群馬県","群馬県"],["埼玉県","埼玉県"],["千葉県","千葉県"],["東京都","東京都"],["神奈川県","神奈川県"],["愛知県","愛知県"],["静岡県","静岡県"],["岐阜県","岐阜県"],["三重県","三重県"],["大阪府","大阪府"],["兵庫県","兵庫県"],["京都府","京都府"],["滋賀県","滋賀県"],["奈良県","奈良県"],["和歌山県","和歌山県"],["岡山県","岡山県"],["広島県","広島県"],["鳥取県","鳥取県"],["島根県","島根県"],["山口県","山口県"],["徳島県","徳島県"],["香川県","香川県"],["愛媛県","愛媛県"],["高知県","高知県"],["福岡県","福岡県"],["佐賀県","佐賀県"],["長崎県","長崎県"],["熊本県","熊本県"],["大分県","大分県"],["宮崎県","宮崎県"],["鹿児島県","鹿児島県"],["沖縄県","沖縄県"]], class: "form-control" %>
</div>
</div>
  <div class="col-sm-6">市区町村</div>
  <div class="form-for input-sm" style="padding: 3px;">
 <%= f.text_field :adress2, class: "form-conrol" %>
  </div>
  </div>
  <div class="col-sm-6">年齢</div>
  <div class="form-for input-sm" style="padding: 3px;">
 <%= f.text_field :age, class: "form-conrol" %>
  </div>
  </div>
  <div class="col-sm-6">子供の人数</div>
  <div class="form-for input-sm" style="padding: 3px;">
 <%= f.text_field :numchild, class: "form-conrol" %>
  </div>
  </div>
  <div class="col-sm-6">お仕事はしていますか？</div>
  <div class="form-for input-sm" style="padding: 3px;">
 <%= f.select :work, [["専業主婦","専業主婦"],["兼業主婦","兼業主婦"]], class: "form-control" %>
  </div>
  </div>
    <div class="col-sm-6">兼業主婦の方に質問です。ご自身や旦那さんの会社名等を話しても大丈夫ですか？</div>
  <div class="form-for input-sm" style="padding: 3px;">
 <%= f.radio_button :private, :はい %>
 <%= f.label :はい %>
  <%= f.radio_button :private, :いいえ %>
 <%= f.label :いいえ %>
  </div>
  </div>
<br><br>

 <h4>ご意見・要望</h4>
　<div class="col-sm-6">どのくらいの頻度で会いたい？</div>
  <div class="form-for input-sm" style="padding: 3px;">
 <%= f.select :frequency, [["月一程度気分転換にお茶しましょう","月一程度気分転換にお茶しましょう"],["週一程度ご飯や買い物をしたいです","週一程度ご飯や買い物をしたいです"],["家族ぐるみで仲良くしましょう","家族ぐるみで仲良くしましょう"],["緊急時は子供を預けあいましょう","緊急時は子供を預けあいましょう"]], class: "form-control" %>
  </div>
  </div>
  <div class="col-sm-6">お誕生日会やイベント事には定期的に参加したい</div>
  <div class="form-for input-sm" style="padding: 3px;">
 <%= f.radio_button :ivent, :参加したい %>
 <%= f.label :参加したい %>
  <%= f.radio_button :ivent, :参加したくない %>
 <%= f.label :参加したくない %>
  </div>
  </div>
　<div class="col-sm-6">呼び方はどうしたいですか</div>
  <div class="form-for input-sm" style="padding: 3px;">
 <%= f.select :lastname, [["あだ名で呼んでください","あだ名で呼んでください"],["「苗字＋さん」で呼んでください","「苗字＋さん」で呼んでください"]] %>
  </div>
  </div>
  <div class="col-sm-6">その他ご意見やメッセージをお願いします</div>
  <div class="form-for input-sm" style="padding: 3px;">
 <%= f.text_area :comment, class: "form-conrol" %>
  </div>
  </div>
<br><br>


      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/users/search.html.erb
<div class = "container-fluid">

<div class="row">
<%= form_tag('/users/search_result', method: :get) do %>
    <div class="col-sm-4">都道府県</div>
    <div class="form-tag input-sm" style="padding: 2px;">
      <select name="add">  
<option value="">都道府県をお選びください。</option>  
<optgroup label="北海道・東北">  
    <option value="北海道">北海道</option>  
    <option value="青森県">青森県</option>  
    <option value="秋田県">秋田県</option>  
    <option value="岩手県">岩手県</option>  
    <option value="山形県">山形県</option>  
    <option value="宮城県">宮城県</option>  
    <option value="福島県">福島県</option>  
</optgroup>  
<optgroup label="甲信越・北陸">  
    <option value="山梨県">山梨県</option>  
    <option value="長野県">長野県</option>  
    <option value="新潟県">新潟県</option>  
    <option value="富山県">富山県</option>  
    <option value="石川県">石川県</option>  
    <option value="福井県">福井県</option>  
</optgroup>  
<optgroup label="関東">  
    <option value="茨城県">茨城県</option>  
    <option value="栃木県">栃木県</option>  
    <option value="群馬県">群馬県</option>  
    <option value="埼玉県">埼玉県</option>  
    <option value="千葉県">千葉県</option>  
    <option value="東京都">東京都</option>  
    <option value="神奈川県">神奈川県</option>  
</optgroup>  
<optgroup label="東海">  
    <option value="愛知県">愛知県</option>  
    <option value="静岡県">静岡県</option>  
    <option value="岐阜県">岐阜県</option>  
    <option value="三重県">三重県</option>  
</optgroup>  
<optgroup label="関西">  
    <option value="大阪府">大阪府</option>  
    <option value="兵庫県">兵庫県</option>  
    <option value="京都府">京都府</option>  
    <option value="滋賀県">滋賀県</option>  
    <option value="奈良県">奈良県</option>  
    <option value="和歌山県">和歌山県</option>  
</optgroup>  
<optgroup label="中国">  
    <option value="岡山県">岡山県</option>  
    <option value="広島県">広島県</option>  
    <option value="鳥取県">鳥取県</option>  
    <option value="島根県">島根県</option>  
    <option value="山口県">山口県</option>  
</optgroup>  
<optgroup label="四国">  
    <option value="徳島県">徳島県</option>  
    <option value="香川県">香川県</option>  
    <option value="愛媛県">愛媛県</option>  
    <option value="高知県">高知県</option>  
</optgroup>  
<optgroup label="九州・沖縄">  
    <option value="福岡県">福岡県</option>  
    <option value="佐賀県">佐賀県</option>  
    <option value="長崎県">長崎県</option>  
    <option value="熊本県">熊本県</option>  
    <option value="大分県">大分県</option>  
    <option value="宮崎県">宮崎県</option>  
    <option value="鹿児島県">鹿児島県</option>  
    <option value="沖縄県">沖縄県</option>  
</optgroup>  
</select>
</div>
</div>
<div class="col-sm-4">年齢を入力してください</div>
<div class="form-tag input-sm" style="padding: 3px;">
<input type="number" name="agemin">才から
<input type="number" name="agemax">才まで
</div>
</div>
<div class="col-sm-4">仕事</div>
<div class="form-tag input-sm" style="padding: 3px;">
<select name="work">  
<option value="">お仕事を選択してください。</option>  
    <option value="専業主婦">専業主婦</option>  
    <option value="兼業主婦">兼業主婦</option>  
</select>
</div>
</div><br>
<div class="center-block" >
<%= submit_tag "検索" %>
</div>
<% end %>
</div>

app/views/users/search_result.html.erb
<div class="container-fluid">
<header class="header header--section">
<h2 class="text-middle">
<i class="icon-movie color-gray-light"></i>検索結果
</h2>
</header>
<%= render partial: "user", collection: @users %>

app/views/users/show.html.erb
<div class="container-fluid">
<div class="showname-box-1" style="border: 10px double #cccccc; padding: 10px; background: #ffffff;">
<h3><%= @user.nickname %>さんのページ<h3>

</div>


   <ul style="list-style:none;">
   
     <li>
         <div>
         <h3 class="text-xsmall text-overflow" title="<%= @user.nickname %>">
             名前　<%= @user.nickname %>
          </h3>
          </div>
     </li>
     <li>
         <div class="thumbnail__caption">
         <h3 class="text-xsmall text-overflow" title="<%= @user.adress1 %>">
             住所（都道府県）<%= @user.adress1 %>
          </h3>
          </div>
     </li>
     <li>
         <div class="thumbnail__caption">
         <h3 class="text-xsmall" title="<%= @user.adress2 %>">
             住所（市区町村）<%= @user.adress2 %>
          </h3>
          </div>
     </li>
     <li>
         <div class="thumbnail__caption">
         <h3 class="text-xsmall text-overflow" title="<%= @user.age %>">
             <%= @user.numchild %>才
          </h3>
          </div>
     </li>
    <li>
         <div class="thumbnail__caption">
         <h3 class="text-xsmall text-overflow" title="<%= @user.numchild %>">
             子供の人数<%= @user.numchild %>人
          </h3>
          </div>
     </li>
    <li>
         <div class="thumbnail__caption">
         <h3 class="text-xsmall text-overflow" title="<%= @user.work %>">
             <%= @user.work %>
          </h3>
          </div>
     </li>
    <li>
    <% if @user.work == "兼業主婦" %>
         <div class="thumbnail__caption">
         <h3 class="text-xsmall text-overflow" title="<%= @user.private %>">
         自分や旦那さんの仕事（会社名等）話しても大丈夫です。
             <%= @user.private %>
          </h3>
          </div>
     </li>
     <% end %>
    <li>
         <div class="thumbnail__caption">
         <h3 class="text-xsmall text-overflow" title="<%= @user.frequency %>">
             <%= @user.frequency %>
          </h3>
          </div>
     </li>
    <li>
         <div class="thumbnail__caption">
         <h3 class="text-xsmall text-overflow" title="<%= @user.ivent %>">
             お誕生日会やイベント事には参加したい？
             <%= @user.ivent %>
          </h3>
          </div>
     </li>
    <li>
         <div class="thumbnail__caption">
         <h3 class="text-xsmall text-overflow" title="<%= @user.lastname %>">
        お名前は何て呼べばいいですか。
             <%= @user.lastname %>
          </h3>
          </div>
     </li>
    <li>
         <div class="thumbnail__caption">
         <h3 class="text-xsmall text-overflow" title="<%= @user.comment %>">
             一言メッセージ　　<%= @user.comment %>
          </h3>
          </div>
    </li>
<br>
    <div class="prof">
      <% if user_signed_in? && @user.be_friend?(current_user)%>
        <%= form_for @group do |f| %>

<!--             <input name="groupgroup[user_ids][]" value=<%= @user.id %> type="hidden"> -->
        <%= f.hidden_field :user_id, value: @user.id %>
        <%= f.submit "友達になる" %>
        <% end %>
      <% end %>
    </div>